<a href="https://colab.research.google.com/github/efh32/TensorFlow-practice/blob/master/DNN_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
# mlp for multiclass classification
from numpy import argmax
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import tensorflow.keras as k
import numpy as np

In [2]:
# load the dataset
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
df = read_csv(path, header=None)
# split into input and output columns
X, y = df.values[:, :-1], df.values[:, -1]

In [3]:
print(X[:10])
print(type(X[0][0]))
print(type(X[0][1]))
print(type(X[0][2]))
print(type(X[0][3]))

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>


In [4]:
# ensure all data are floating point values
X = X.astype('float32')
print(type(X[0][0]))
print(type(X[0][1]))
print(type(X[0][2]))
print(type(X[0][3]))

<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>


In [5]:
print(y[:10])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [6]:
# encode strings to integer
y = LabelEncoder().fit_transform(y)
print(y[:10])
print(y[-10:])
print(len(y))
print(y[75:85])

[0 0 0 0 0 0 0 0 0 0]
[2 2 2 2 2 2 2 2 2 2]
150
[1 1 1 1 1 1 1 1 1 1]


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [8]:
print(y_train)

[2 2 1 1 1 0 0 1 2 1 2 1 0 0 2 1 2 1 0 0 2 2 0 2 0 0 1 2 2 1 2 0 1 1 2 1 1
 2 0 2 1 0 1 0 1 2 2 0 0 0 2 1 0 0 0 1 1 1 0 2 2 0 2 1 0 0 0 2 0 2 0 2 1 0
 2 2 1 1 2 2 0 2 2 2 1 2 1 2 2 1 1 1 0 0 2 0 0 2 1 0]


In [9]:
print(X_train.shape)

(100, 4)


In [10]:
n_features = X_train.shape[1]
print(n_features)

4


In [11]:
print(X_train.shape[0])

100


In [12]:
print(X_train.shape[-1])
print(X_train.shape[-2])

4
100


In [13]:
# define model
model = Sequential()
model.add(Dense(10, activation='relu', kernel_initializer='he_normal', input_shape=(n_features,), name='layer1'))
model.add(Dense(8, activation='relu', kernel_initializer='he_normal', name='layer2'))
model.add(Dense(5, activation='relu', kernel_initializer='he_normal', name='layer3'))
model.add(Dense(3, activation='softmax', name='softmax_layer'))

In [14]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (None, 10)                50        
_________________________________________________________________
layer2 (Dense)               (None, 8)                 88        
_________________________________________________________________
layer3 (Dense)               (None, 5)                 45        
_________________________________________________________________
softmanx_layer (Dense)       (None, 3)                 18        
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________
None


In [16]:
# compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# fit the model
model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=0)
# evaluate the model
loss, acc = model.evaluate(X_test, y_test, verbose=0)

In [17]:
print(model.weights)

[<tf.Variable 'layer1/kernel:0' shape=(4, 10) dtype=float32, numpy=
array([[ 0.5947839 , -0.41960028,  0.19726996,  0.3407105 , -0.05250696,
         0.06376611, -0.9903498 , -0.8910181 , -0.11515204, -0.6849415 ],
       [-0.00168907, -0.57038754, -0.6019411 ,  0.09353954,  1.5500998 ,
        -0.42658785,  0.3788401 , -0.35804683, -0.1195932 , -1.0014108 ],
       [ 1.2260422 , -1.1740804 ,  0.25694013,  0.6696063 , -0.7273707 ,
         1.3361243 , -0.01268508,  0.38900086, -0.03100165, -0.8857637 ],
       [-0.80117726,  0.55864257,  0.32788917, -0.89655995, -0.5944501 ,
         1.138713  ,  0.36818144,  0.06747258, -0.57655674,  0.82553166]],
      dtype=float32)>, <tf.Variable 'layer1/bias:0' shape=(10,) dtype=float32, numpy=
array([ 0.09328666,  0.        , -0.08227021,  0.15418619,  0.48139596,
       -0.10603895,  0.        ,  0.        ,  0.        ,  0.        ],
      dtype=float32)>, <tf.Variable 'layer2/kernel:0' shape=(10, 8) dtype=float32, numpy=
array([[ 0.40189344,  

In [18]:
print(X_test[0])
print(y_test[0])

[5.8 2.8 5.1 2.4]
2


In [23]:
model_l1 = k.models.Model(inputs=model.input, outputs=model.get_layer('layer1').output)

In [27]:
print(X_test[0].shape)
print(model.input)

(4,)
Tensor("layer1_input:0", shape=(None, 4), dtype=float32)


In [31]:
test1 = np.array([X_test[0]])
print(test1.shape)

(1, 4)


In [32]:
model_l1.predict(test1)

array([[7.8682933, 0.       , 1.4737892, 3.655466 , 0.       , 8.616504 ,
        0.       , 0.       , 0.       , 0.       ]], dtype=float32)

In [37]:
model_l2 = k.models.Model(inputs=model.input, outputs=model.get_layer('layer2').output)

In [39]:
model_l2.predict(test1)

array([[0.       , 7.7726693, 0.       , 0.       , 0.       , 0.9840584,
        0.       , 0.       ]], dtype=float32)

In [51]:
layer2_weights = model.get_layer('layer2').get_weights()
print(layer2_weights)

[array([[ 0.40189344,  0.06878303,  0.07361549,  0.11103338, -0.12353898,
         0.71880674,  0.14466761, -0.66364366],
       [ 0.7441133 , -0.10733938, -0.0133907 , -0.40280256,  0.7707257 ,
        -0.195893  , -0.11211708,  0.24927907],
       [-0.7019519 ,  1.1507823 ,  0.03064272,  0.31162667,  0.37665832,
        -0.2811802 ,  0.32006982,  0.29995847],
       [ 0.25444785,  0.02284961, -0.8449968 , -0.16562672,  0.08223266,
         0.17093207, -0.98257154, -0.607555  ],
       [ 0.9100939 , -0.17560163,  0.37448955, -0.57808214, -0.6279049 ,
        -0.19533242,  0.34582135, -0.57565224],
       [-0.45503107,  0.6317265 , -0.5539862 , -0.12340034, -0.00530899,
        -0.5609822 , -0.53370225,  0.27983806],
       [ 0.06728395,  0.25712606,  0.67033285,  0.0746287 ,  0.3706839 ,
        -0.58052427, -0.91885835,  0.14731137],
       [-0.28026003,  0.02415845,  0.07046339,  0.50673544,  0.42461228,
         0.657771  , -0.29019982,  0.22279365],
       [-0.36943468, -0.6283122

In [52]:
print(layer2_weights[0])

[[ 0.40189344  0.06878303  0.07361549  0.11103338 -0.12353898  0.71880674
   0.14466761 -0.66364366]
 [ 0.7441133  -0.10733938 -0.0133907  -0.40280256  0.7707257  -0.195893
  -0.11211708  0.24927907]
 [-0.7019519   1.1507823   0.03064272  0.31162667  0.37665832 -0.2811802
   0.32006982  0.29995847]
 [ 0.25444785  0.02284961 -0.8449968  -0.16562672  0.08223266  0.17093207
  -0.98257154 -0.607555  ]
 [ 0.9100939  -0.17560163  0.37448955 -0.57808214 -0.6279049  -0.19533242
   0.34582135 -0.57565224]
 [-0.45503107  0.6317265  -0.5539862  -0.12340034 -0.00530899 -0.5609822
  -0.53370225  0.27983806]
 [ 0.06728395  0.25712606  0.67033285  0.0746287   0.3706839  -0.58052427
  -0.91885835  0.14731137]
 [-0.28026003  0.02415845  0.07046339  0.50673544  0.42461228  0.657771
  -0.29019982  0.22279365]
 [-0.36943468 -0.6283122  -0.07631729  0.20427443  0.770457   -0.4251421
  -0.00935573 -0.18735938]
 [ 0.20316698 -0.3623321  -0.08159311 -0.01935619  0.15241726  0.14207108
   0.7922499  -0.0324150

In [53]:
print(layer2_weights[0].shape)

(10, 8)


In [54]:
test1_layer1_output = model_l1.predict(test1)

In [56]:
print(np.dot(test1_layer1_output, layer2_weights[0]))

[[-0.8629651   7.764015   -7.237892   -0.33580709 -0.16207212  1.0325127
  -6.5804024  -4.5893383 ]]


In [57]:
print(np.dot(test1_layer1_output, layer2_weights[0])+ layer2_weights[1])

[[-0.4731525   7.7726693  -7.237892   -0.33536443 -0.1819893   0.9840584
  -6.5804024  -4.5893383 ]]


In [58]:
print(k.activations.relu(np.dot(test1_layer1_output, layer2_weights[0])+ layer2_weights[1]))

tf.Tensor(
[[0.        7.7726693 0.        0.        0.        0.9840584 0.
  0.       ]], shape=(1, 8), dtype=float32)


Test third layer output

In [60]:
model_l3 = k.models.Model(inputs=model.input, outputs=model.get_layer('layer3').output)

In [61]:
model_l3.predict(test1)

array([[6.2441783, 0.       , 6.4815   , 5.0263743, 0.       ]],
      dtype=float32)

In [62]:
layer3_weights = model.get_layer('layer3').get_weights()


In [63]:
test1_layer2_output = model_l2.predict(test1)

In [64]:
print(k.activations.relu(np.dot(test1_layer2_output, layer3_weights[0])+ layer3_weights[1]))

tf.Tensor([[6.2441783 0.        6.4815    5.0263743 0.       ]], shape=(1, 5), dtype=float32)


Test last layer output

In [65]:
model.predict(test1)

array([[1.7492002e-04, 2.2346051e-03, 9.9759054e-01]], dtype=float32)

In [67]:
layer4_weights = model.get_layer('softmax_layer').get_weights()

In [68]:
test1_layer3_output = model_l3.predict(test1)

In [74]:
print(np.dot(test1_layer3_output, layer4_weights[0])+ layer4_weights[1])

[[-7.619489  -5.071997   1.0292808]]


In [80]:
import scipy
print(scipy.special.softmax(np.dot(test1_layer3_output, layer4_weights[0])+ layer4_weights[1]))

[[1.7491994e-04 2.2346065e-03 9.9759048e-01]]


In [83]:
test1_presoft = np.dot(test1_layer3_output, layer4_weights[0])+ layer4_weights[1]

print(test1_presoft)

print(k.activations.softmax(test1_presoft))

[[-7.619489  -5.071997   1.0292808]]


AttributeError: ignored